# Workshop Design of Beams and Elements under combined loads

As we are not going to do a final exam, this workshop will reinforce your knowledge on design of beams and elements under combined loads 


## Exercise 1

Forces are applied at points A and B of the solid cast-iron bracket shown. Knowing that the bracket has a diameter of 0.8 in., determine the principal stresses and the maximum shearing stress at (a) point H, (b) point K.

![image1](8-41.png)

Please consider the following values for each:

In [1]:
import numpy as np
import pandas as pd
lock = False
if lock:
    classlist = pd.read_excel('classlist2021I.xlsx')
    classlist = classlist.drop('Nivel', axis=1)

    A = np.random.choice(np.arange(1500, 3500, 6),20) # lb
    B = np.random.choice(np.linspace(1.5, 3.5, 6),20) # in
    C = np.random.choice(np.arange(500, 1000, 6),20) # lb
    D = np.random.choice(np.linspace(2.0, 4.0, 6),20) # in
    E = np.random.choice(np.linspace(0.5, 1.5, 6),20) # in
    var_d = {'A':A,'B':B,'C':C,'D':D, 'E':E}

    for key, item in var_d.items():
        classlist[key] = np.random.choice(item,20)

    classlist = classlist.round(3)
    classlist.to_csv('problem1.csv')
else:
    classlist = pd.read_csv('problem1.csv')
classlist

,Unnamed: 0,ID,Nombre,A,B,C,D,E
0,0,30000048165,"ACERO ROJAS,DANIEL FELIPE",1830,2.7,956,2.4,0.7
1,1,30000022560,"ACOSTA SICHACA,PAULA DANIELA",1836,1.9,764,4.0,0.7
2,2,30000050321,"AREVALO DUEÑAS,TATIANA DANIELA",3228,1.9,920,2.0,1.3
3,3,30000045911,"BUITRAGO PACHON,ANDRES FABIAN",2598,1.5,620,2.0,1.1
4,4,30000050269,"CASAS GONZÁLEZ,CRISTIAN ESTEVEN",2682,1.9,842,2.0,1.5
5,5,30000050883,"ESTÉVEZ MONCADA,JOHAN SEBASTIÁN",1920,2.7,680,2.4,0.7
6,6,20141614093,"FANDIÑO ACOSTA,NICOLÁS ALBERTO",2682,1.9,764,3.6,0.5
7,7,30000048970,"GARCIA RODRIGUEZ,ANDRES FELIPE",2616,2.3,680,3.6,1.3
8,8,30000050168,"GARCÍA MARTINEZ,EDUARD CAMILO",2682,2.7,596,2.0,0.7
9,9,30000050740,"GÓMEZ CORTÉS,JUAN PABLO",2742,3.1,950,2.0,0.7
10,10,30000048121,"PARRA MADRIGAL,JUAN GILBERTO",3198,2.3,566,2.0,0.7
11,11,30000047725,"PEREZ CORTES,ANDRES FELIPE",1830,2.7,968,4.0,1.5
12,12,30000048147,"PONTON VELA,NILSON DAVID",1920,2.3,782,2.0,0.9
13,13,30000030089,"PORTUGUEZ TORRES,EDUARD ALEXIS",3198,1.9,662,3.6,0.9
14,14,30000058190,"QUIROGA LANDAZABAL,EMMANUEL",3198,1.9,884,2.0,0.9
15,15,30000049546,"RODRIGUEZ ORDUZ,JUAN SEBASTIAN",3300,2.3,680,2.8,0.9
16,16,30000024873,"ROJAS COLMENARES,ANGEL ESTEBAN",3228,2.7,950,3.6,0.5
17,17,30000051687,"TICORA GONZALEZ,JONATHAN FELIPE",3300,1.9,920,2.8,0.9
18,18,30000047652,"VILLAMIL TORRES,JORGE ELIECER ALFREDO",1920,1.9,842,2.0,0.5
19,19,30000057249,"VILLEGAS BARRANCO,KAREN SOFIA",3228,2.7,596,2.0,0.5

## Exercise 2

Three forces are applied to the bar shown. Determine the normal and shearing stresses at (a) point a, (b) point b, (c) point c.

![image2](8-47.png)

In [2]:
lock = False
if lock:
    classlist2 = pd.read_excel('classlist2021I.xlsx')
    classlist2 = classlist2.drop('Nivel', axis=1)

    F = np.random.choice(np.arange(50, 100, 6),20) # mm
    G = np.random.choice(np.arange(15,30, 6),20) # mm
    H = np.random.choice(np.arange(150, 300, 6),20) # mm
    I = np.random.choice(np.arange(600, 1000, 6),20) # I
    J = np.random.choice(np.arange(300,1000, 6),20) # N
    K = np.random.choice(np.arange(5, 30, 6),20) # KN
    var_d = {'F':F,'G':G,'H':H,'I':I, 'J':J, 'K':K}

    for key, item in var_d.items():
        classlist2[key] = np.random.choice(item,20)

    classlist2 = classlist2.round(3)
    classlist2.to_csv('problem2.csv')
else:
    classlist2 = pd.read_csv('problem2.csv')
classlist2

,Unnamed: 0,ID,Nombre,F,G,H,I,J,K
0,0,30000048165,"ACERO ROJAS,DANIEL FELIPE",86,15,234,618,906,11
1,1,30000022560,"ACOSTA SICHACA,PAULA DANIELA",98,21,180,942,714,17
2,2,30000050321,"AREVALO DUEÑAS,TATIANA DANIELA",62,15,180,618,714,11
3,3,30000045911,"BUITRAGO PACHON,ANDRES FABIAN",74,27,192,834,378,11
4,4,30000050269,"CASAS GONZÁLEZ,CRISTIAN ESTEVEN",56,15,192,708,396,17
5,5,30000050883,"ESTÉVEZ MONCADA,JOHAN SEBASTIÁN",50,15,198,876,762,23
6,6,20141614093,"FANDIÑO ACOSTA,NICOLÁS ALBERTO",98,15,168,942,852,5
7,7,30000048970,"GARCIA RODRIGUEZ,ANDRES FELIPE",56,21,168,996,714,23
8,8,30000050168,"GARCÍA MARTINEZ,EDUARD CAMILO",68,27,162,798,546,17
9,9,30000050740,"GÓMEZ CORTÉS,JUAN PABLO",68,15,192,780,714,11
10,10,30000048121,"PARRA MADRIGAL,JUAN GILBERTO",98,21,162,834,960,23
11,11,30000047725,"PEREZ CORTES,ANDRES FELIPE",98,27,180,834,906,23
12,12,30000048147,"PONTON VELA,NILSON DAVID",80,15,192,798,972,5
13,13,30000030089,"PORTUGUEZ TORRES,EDUARD ALEXIS",50,15,282,792,906,5
14,14,30000058190,"QUIROGA LANDAZABAL,EMMANUEL",86,21,216,912,960,17
15,15,30000049546,"RODRIGUEZ ORDUZ,JUAN SEBASTIAN",92,27,192,882,336,23
16,16,30000024873,"ROJAS COLMENARES,ANGEL ESTEBAN",86,15,216,780,906,5
17,17,30000051687,"TICORA GONZALEZ,JONATHAN FELIPE",98,15,216,978,336,5
18,18,30000047652,"VILLAMIL TORRES,JORGE ELIECER ALFREDO",86,27,234,708,936,5
19,19,30000057249,"VILLEGAS BARRANCO,KAREN SOFIA",62,15,192,996,312,5

## Exercise 3

Take the following figure as reference:

![image3](8-55-56.png)

Two forces P1 and P2 are applied as shown in directions perpen- dicular to the longitudinal axis of a W310 × 60 beam. Knowing that P1 = X kN and P2 = Y kN, determine the principal stresses and the maximum shearing stress at point a and b. X and Y are your last and last-last code number multiplied by 5. Consider 25 kN if any of those are 0.

Regards.